function render(view,title,subtitle){return(req,res)=>res.render(view,{title,subtitle});}
module.exports={
  login:render("login","Sign in","B2B operations access"),
  dashboard:render("dashboard","Dashboard","Distribution operations at a glance"),
  customers:render("customers","Customers","Retailers, wholesalers and business accounts"),
  products:render("products","Products","SKU catalogue, tax and product media"),
  productNew:render("product-form","New product","Create a connected B2B catalogue product"),
  productDetail:render("product-detail","Product","Product detail, rich description, gallery and supplier sourcing"),
  productEdit:render("product-form","Edit product","Update product master and rich description"),
  suppliers:render("suppliers","Suppliers","Supplier locations and sourcing relationships"),
  pricing:render("pricing","Customer pricing","Negotiated SKU prices and approvals"),
  procurement:render("procurement","Procurement","Purchase orders"),
  procurementDemand:render("procurement-demand","Procurement demand","Sales-order shortages waiting for sourcing"),
  procurementNew:render("procurement-form","New purchase order","Create a purchase order from demand or manually"),
  procurementDetail:render("procurement-detail","Purchase order","Purchase order detail and linked sales demand"),
  procurementReceive:render("procurement-receive","Receive goods","Record GRN and supplier invoice"),
  inventory:render("inventory","Inventory","Warehouse stock balances"),
  inventoryMovements:render("inventory-movements","Inventory movements","Immutable stock movement ledger"),
  inventoryAdjust:render("inventory-adjust","Inventory adjustment","Audited manual stock adjustment"),
  warehouses:render("warehouses","Warehouses","Stock locations and fulfilment origins"),
  warehouseNew:render("warehouse-form","New warehouse","Create a fulfilment location"),
  warehouseEdit:render("warehouse-form","Edit warehouse","Update a fulfilment location"),
  orders:render("orders","Sales orders","Customer distribution orders"),
  orderNew:render("order-form","New sales order","Create a connected customer distribution order"),
  orderDetail:render("order-detail","Sales order","Connected order, sourcing, warehouse and delivery view"),
  orderProcurement:render("order-procurement","Source sales order","Allocate shortage quantities across suppliers"),
  orderFulfilment:render("order-fulfilment","Fulfil sales order","Warehouse fulfilment workflow"),
  delivery:render("delivery","Delivery","Internal and third-party assignment"),
  deliveryAssign:render("delivery-assign","Assign delivery","Guided order, warehouse, product and driver assignment"),
  deliveryDetail:render("delivery-detail","Delivery detail","Connected delivery record and operational timeline"),
  deliveryUpdate:render("delivery-update","Update delivery","Guided delivery status workflow"),
  finance:render("finance","Finance","Receivables, payables and payments"),
  returns:render("returns","Returns","Customer and supplier returns"),
  reports:render("reports","Reports","Sales, procurement and cash summary"),
  employees:render("employees","Employees","B2B employee access"),
  roles:render("roles","Roles & permissions","Fine-grained B2B permissions"),
  storage:render("storage","File Manager","B2B S3 uploads and downloads"),
  audit:render("audit","Audit Trail","Sensitive commercial and operational changes"),
  invoice:render("invoice","Invoice","HTML invoice")
};
