const customer=require("../services/customer-service");const customer360=require("../services/customer-360-service");const product=require("../services/product-service");const supplier=require("../services/supplier-service");const pricing=require("../services/pricing-service");const employee=require("../services/employee-service");const audit=require("../services/audit-service");
async function run(res,next,fn,status=200){try{return res.status(status).json({success:true,data:await fn()});}catch(e){return next(e);}}
module.exports={
 customerList:(req,res,next)=>run(res,next,()=>customer.list(req.query)),customer360:(req,res,next)=>run(res,next,()=>customer360.get(req.params.id)),customerGet:(req,res,next)=>run(res,next,()=>customer.get(req.params.id)),customerCreate:(req,res,next)=>run(res,next,async()=>{const x=await customer.create(req.body,req.admin.employeeId);await audit.record(req,{action:"customer.create",entityType:"customer",entityId:x.customerId,after:x});return x;},201),customerUpdate:(req,res,next)=>run(res,next,async()=>{const before=await customer.get(req.params.id);const x=await customer.update(req.params.id,req.body,req.admin.employeeId);await audit.record(req,{action:"customer.update",entityType:"customer",entityId:x.customerId,before,after:x});return x;}),
 productList:(req,res,next)=>run(res,next,()=>product.list(req.query)),productGet:(req,res,next)=>run(res,next,()=>product.get(req.params.id)),productCreate:(req,res,next)=>run(res,next,async()=>{const x=await product.create(req.body,req.admin.employeeId);await audit.record(req,{action:"product.create",entityType:"product",entityId:x.productId,after:x});return x;},201),productUpdate:(req,res,next)=>run(res,next,async()=>{const before=await product.get(req.params.id);const x=await product.update(req.params.id,req.body,req.admin.employeeId);await audit.record(req,{action:"product.update",entityType:"product",entityId:x.productId,before,after:x});return x;}),productMedia:(req,res,next)=>run(res,next,()=>product.addMedia(req.params.id,req.body,req.admin.employeeId),201),
 supplierList:(req,res,next)=>run(res,next,()=>supplier.list(req.query)),supplierGet:(req,res,next)=>run(res,next,()=>supplier.get(req.params.id)),supplierCreate:(req,res,next)=>run(res,next,async()=>{const x=await supplier.create(req.body,req.admin.employeeId);await audit.record(req,{action:"supplier.create",entityType:"supplier",entityId:x.supplierId,after:x});return x;},201),supplierUpdate:(req,res,next)=>run(res,next,()=>supplier.update(req.params.id,req.body,req.admin.employeeId)),supplierLocation:(req,res,next)=>run(res,next,()=>supplier.addLocation(req.params.id,req.body,req.admin.employeeId),201),supplierOffer:(req,res,next)=>run(res,next,()=>supplier.upsertOffer(req.body,req.admin.employeeId),201),purchasePriceHistory:(req,res,next)=>run(res,next,()=>supplier.purchasePriceHistory(req.query)),productOffers:(req,res,next)=>run(res,next,()=>supplier.offersByProduct(req.params.id)),
 priceList:(req,res,next)=>run(res,next,()=>pricing.list(req.query)),priceCreate:(req,res,next)=>run(res,next,()=>pricing.create(req.body,req.admin),201),priceApprove:(req,res,next)=>run(res,next,()=>pricing.approve(req.params.id,req.admin,req.body.status||"approved")),
 employeeList:(req,res,next)=>run(res,next,()=>employee.listEmployees(req.query)),employeeCreate:(req,res,next)=>run(res,next,()=>employee.createEmployee(req.body,req.admin.employeeId),201),employeeUpdate:(req,res,next)=>run(res,next,()=>employee.updateEmployee(req.params.id,req.body,req.admin.employeeId)),roleList:(req,res,next)=>run(res,next,()=>employee.listRoles()),roleCreate:(req,res,next)=>run(res,next,()=>employee.createRole(req.body,req.admin.employeeId),201),roleUpdate:(req,res,next)=>run(res,next,()=>employee.updateRole(req.params.id,req.body,req.admin.employeeId))
};
