const storage=require("../services/storage/s3-service");
async function config(req,res,next){try{return res.json({success:true,data:storage.publicConfig()});}catch(e){return next(e)}}
async function upload(req,res,next){try{return res.status(201).json({success:true,data:await storage.createUploadUrl(req.body)});}catch(e){return next(e)}}
async function download(req,res,next){try{return res.json({success:true,data:await storage.createDownloadUrl(req.body)});}catch(e){return next(e)}}
function productPrefix(kind){const cfg=storage.publicConfig();return kind==="document"?cfg.privatePrefix+"products/":cfg.publicPrefix+"products/";}
function assertProductKey(key){const cfg=storage.publicConfig(),value=String(key||"");if(!value.startsWith(cfg.publicPrefix+"products/")&&!value.startsWith(cfg.privatePrefix+"products/"))throw Object.assign(new Error("Product file key is invalid"),{status:400});return value;}function businessPrefix(area){const cfg=storage.publicConfig(),allowed={customers:"customers/",suppliers:"suppliers/",invoices:"invoices/",returns:"returns/"};if(!allowed[area])throw Object.assign(new Error("Attachment area is invalid"),{status:400});return cfg.privatePrefix+allowed[area];}function assertBusinessKey(area,key){const value=String(key||""),prefix=businessPrefix(area);if(!value.startsWith(prefix))throw Object.assign(new Error("Attachment file key is invalid"),{status:400});return value;}function businessUpload(area){return async(req,res,next)=>{try{return res.status(201).json({success:true,data:await storage.createUploadUrl({...req.body,prefix:businessPrefix(area)})});}catch(e){return next(e)}}}function businessDownload(area){return async(req,res,next)=>{try{return res.json({success:true,data:await storage.createDownloadUrl({key:assertBusinessKey(area,req.body?.key)})});}catch(e){return next(e)}}}
async function productUpload(req,res,next){try{return res.status(201).json({success:true,data:await storage.createUploadUrl({...req.body,prefix:productPrefix(req.body?.kind)})});}catch(e){return next(e)}}
async function productDownload(req,res,next){try{return res.json({success:true,data:await storage.createDownloadUrl({key:assertProductKey(req.body?.key)})});}catch(e){return next(e)}}
module.exports={config,upload,download,productUpload,productDownload,customerUpload:businessUpload("customers"),customerDownload:businessDownload("customers"),supplierUpload:businessUpload("suppliers"),supplierDownload:businessDownload("suppliers"),invoiceUpload:businessUpload("invoices"),invoiceDownload:businessDownload("invoices"),returnUpload:businessUpload("returns"),returnDownload:businessDownload("returns")};
