const crypto=require("crypto");const path=require("path");const {validationError,textValue}=require("../../utils/validation");
function config(){const region=String(process.env.AWS_REGION||"").trim(),bucket=String(process.env.AWS_S3_BUCKET||"").trim(),accessKeyId=String(process.env.AWS_ACCESS_KEY_ID||"").trim(),secretAccessKey=String(process.env.AWS_SECRET_ACCESS_KEY||"").trim(),sessionToken=String(process.env.AWS_SESSION_TOKEN||"").trim();const publicPrefix=normalizeRoot(process.env.AWS_S3_PUBLIC_PREFIX||"public/b2b/"),privatePrefix=normalizeRoot(process.env.AWS_S3_PRIVATE_PREFIX||"private/b2b/");return{region,bucket,credentials:{accessKeyId,secretAccessKey,sessionToken},publicPrefix,privatePrefix,roots:[publicPrefix,privatePrefix],cloudFrontDomain:String(process.env.AWS_CLOUDFRONT_DOMAIN||"").replace(/^https?:\/\//,"").replace(/\/$/,""),maxUploadBytes:Math.max(1,Number(process.env.S3_MAX_UPLOAD_MB||20))*1024*1024,configured:Boolean(region&&bucket&&accessKeyId&&secretAccessKey)};}
function normalizeRoot(value){const v=String(value||"").trim().replace(/^\/+/,"").replace(/\\/g,"/");if(!v||v.split("/").includes(".."))throw new Error("Invalid S3 prefix");return v.endsWith("/")?v:`${v}/`;}
function publicConfig(){const c=config();return{configured:c.configured,region:c.region,bucket:c.bucket,publicPrefix:c.publicPrefix,privatePrefix:c.privatePrefix,maxUploadMb:c.maxUploadBytes/1024/1024,cloudFrontDomain:c.cloudFrontDomain};}
function assertConfigured(){const c=config();if(!c.configured)throw Object.assign(new Error("Amazon S3 is not configured"),{status:503,code:"S3_NOT_CONFIGURED",expose:true});return c;}
function normalizePrefix(value){const c=config();let v=String(value||c.privatePrefix).trim().replace(/\\/g,"/").replace(/^\/+/,"");if(v.split("/").some(x=>x===".."||x==="."))throw validationError("Folder path is invalid");if(!v.endsWith("/"))v+="/";if(!c.roots.some(root=>v===root||v.startsWith(root)))throw validationError("Folder is outside approved B2B S3 prefixes");return v;}
function safeName(value){const name=textValue(value,{label:"File name",required:true,maxLength:255});if(/[\\/\0\r\n<>:"|?*]/.test(name)||name.startsWith("."))throw validationError("File name contains unsupported characters");return name;}
function awsEncode(v){return encodeURIComponent(String(v)).replace(/[!'()*]/g,ch=>`%${ch.charCodeAt(0).toString(16).toUpperCase()}`);}
function encodeKey(key){return String(key).split("/").map(awsEncode).join("/");}
function sha256(v){return crypto.createHash("sha256").update(v).digest("hex");}function hmac(key,v,enc){return crypto.createHmac("sha256",key).update(v).digest(enc);}function signingKey(secret,date,region){const d=hmac(`AWS4${secret}`,date),r=hmac(d,region),s=hmac(r,"s3");return hmac(s,"aws4_request");}
function canonicalQuery(params){return[...params.entries()].map(([k,v])=>[awsEncode(k),awsEncode(v)]).sort((a,b)=>a[0].localeCompare(b[0])||a[1].localeCompare(b[1])).map(([k,v])=>`${k}=${v}`).join("&");}
function timestamp(date=new Date()){const iso=date.toISOString().replace(/[:-]|\.\d{3}/g,"");return{amzDate:iso,dateStamp:iso.slice(0,8)};}
function endpoint(c,key=""){return new URL(`https://${c.bucket}.s3.${c.region}.amazonaws.com/${encodeKey(key)}`);}
function presignedUrl(c,method,key,{headers={},query={},expiresIn=300}={}){const url=endpoint(c,key);for(const[k,v]of Object.entries(query))if(v!==undefined&&v!==null&&v!=="")url.searchParams.append(k,String(v));const{amzDate,dateStamp}=timestamp(),scope=`${dateStamp}/${c.region}/s3/aws4_request`;const signedHeaders=["host",...Object.keys(headers).map(x=>x.toLowerCase())].sort();const values={host:url.host};for(const[k,v]of Object.entries(headers))values[k.toLowerCase()]=String(v).trim();url.searchParams.set("X-Amz-Algorithm","AWS4-HMAC-SHA256");url.searchParams.set("X-Amz-Credential",`${c.credentials.accessKeyId}/${scope}`);url.searchParams.set("X-Amz-Date",amzDate);url.searchParams.set("X-Amz-Expires",String(expiresIn));url.searchParams.set("X-Amz-SignedHeaders",signedHeaders.join(";"));if(c.credentials.sessionToken)url.searchParams.set("X-Amz-Security-Token",c.credentials.sessionToken);const canonicalHeaders=signedHeaders.map(k=>`${k}:${values[k]}\n`).join("");const request=[method,url.pathname,canonicalQuery(url.searchParams),canonicalHeaders,signedHeaders.join(";"),"UNSIGNED-PAYLOAD"].join("\n");const toSign=["AWS4-HMAC-SHA256",amzDate,scope,sha256(request)].join("\n");const signature=hmac(signingKey(c.credentials.secretAccessKey,dateStamp,c.region),toSign,"hex");url.searchParams.set("X-Amz-Signature",signature);url.search=[...url.searchParams.entries()].map(([k,v])=>`${awsEncode(k)}=${awsEncode(v)}`).sort().join("&");return url.toString();}
function publicUrl(key,c=config()){return c.cloudFrontDomain&&key.startsWith(c.publicPrefix)?`https://${c.cloudFrontDomain}/${encodeKey(key)}`:"";}
async function createUploadUrl(input={}){const c=assertConfigured(),prefix=normalizePrefix(input.prefix||`${c.publicPrefix}products/`),fileName=safeName(input.fileName),size=Number(input.sizeBytes||0);if(!Number.isInteger(size)||size<1||size>c.maxUploadBytes)throw validationError("File size is outside allowed limit");const ext=path.extname(fileName).toLowerCase();const allowed=new Set([".jpg",".jpeg",".png",".webp",".pdf",".doc",".docx",".xls",".xlsx",".csv",".txt"]);if(!allowed.has(ext))throw validationError("File type is not allowed");const contentType=textValue(input.contentType,{label:"Content type",required:true,maxLength:200}),key=`${prefix}${fileName}`,headers={"content-type":contentType};return{key,method:"PUT",headers,url:presignedUrl(c,"PUT",key,{headers,expiresIn:300}),publicUrl:publicUrl(key,c)};}
async function createDownloadUrl(input={}){const c=assertConfigured(),key=textValue(input.key,{label:"S3 key",required:true,maxLength:1500});if(!c.roots.some(root=>key.startsWith(root)))throw validationError("File is outside approved B2B S3 prefixes");if(key.startsWith(c.publicPrefix)&&publicUrl(key,c))return{key,url:publicUrl(key,c),public:true};return{key,url:presignedUrl(c,"GET",key,{expiresIn:300}),public:false};}
module.exports={config,publicConfig,normalizePrefix,createUploadUrl,createDownloadUrl,presignedUrl,publicUrl};
