const Customer=require("../models/Customer"); const CustomerUser=require("../models/CustomerUser"); const Employee=require("../models/Employee"); const {pageQuery,escapedRegex}=require("../utils/pagination"); const {textValue,mobileValue,emailValue}=require("../utils/validation");
function address(input={},label="Address"){return{label:String(input.label||""),line1:textValue(input.line1,{label:`${label} line 1`,required:true,maxLength:250}),line2:String(input.line2||"").trim().slice(0,250),city:textValue(input.city,{label:`${label} city`,required:true,maxLength:120}),state:textValue(input.state,{label:`${label} state`,required:true,maxLength:120}),pincode:textValue(input.pincode,{label:`${label} pincode`,required:true,maxLength:6}),contactName:String(input.contactName||"").trim().slice(0,120),contactMobile:String(input.contactMobile||"").replace(/\D/g,"").slice(-10),isDefault:Boolean(input.isDefault)}}
async function list(query={}){const {page,limit,skip}=pageQuery(query); const filter={}; if(query.status)filter.status=query.status; if(query.type)filter.customerType=query.type; if(query.assignedEmployeeId)filter.assignedEmployeeId=query.assignedEmployeeId; if(query.search){const rx=new RegExp(escapedRegex(query.search),"i");filter.$or=[{businessName:rx},{contactName:rx},{mobile:rx},{gstin:rx}];} const [items,total]=await Promise.all([Customer.find(filter).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Customer.countDocuments(filter)]);return{items,page,limit,total,pages:Math.ceil(total/limit)||1};}
async function get(customerId){const item=await Customer.findOne({customerId}).lean(); if(!item)throw Object.assign(new Error("Customer not found"),{status:404});return item;}
async function ensureMobileAvailable(mobile,customerId=""){const existing=await Customer.findOne({normalizedMobile:mobile,...(customerId?{customerId:{$ne:customerId}}:{})}).select({customerId:1,businessName:1}).lean();if(existing)throw Object.assign(new Error("This mobile number is already assigned to another B2B customer"),{status:409,code:"CUSTOMER_MOBILE_IN_USE"});}
async function syncUser(customer){if(!customer.portalAccessEnabled){await CustomerUser.updateMany({customerId:customer.customerId},{$set:{status:"inactive"}});return null;} const mobile=customer.normalizedMobile;await CustomerUser.updateMany({customerId:customer.customerId,normalizedMobile:{$ne:mobile}},{$set:{status:"inactive"}});const owned=await CustomerUser.findOne({normalizedMobile:mobile,customerId:{$ne:customer.customerId}}).lean();if(owned)throw Object.assign(new Error("This mobile number is already linked to another customer portal account"),{status:409,code:"CUSTOMER_PORTAL_MOBILE_IN_USE"});return CustomerUser.findOneAndUpdate({normalizedMobile:mobile},{$set:{customerId:customer.customerId,mobile,name:customer.contactName,status:customer.status==="active"?"active":"inactive"}},{upsert:true,new:true,setDefaultsOnInsert:true});}
async function create(input,actor){const mobile=mobileValue(input.mobile);await ensureMobileAvailable(mobile); const billing=address(input.billingAddress||{},"Billing address"); const customer=await Customer.create({businessName:textValue(input.businessName,{label:"Business name",required:true,maxLength:180}),customerType:input.customerType||"retailer",contactName:textValue(input.contactName,{label:"Contact name",required:true,maxLength:120}),mobile,normalizedMobile:mobile,email:emailValue(input.email),gstin:String(input.gstin||"").trim().toUpperCase(),billingAddress:billing,deliveryAddresses:Array.isArray(input.deliveryAddresses)?input.deliveryAddresses.map((x,i)=>address(x,`Delivery address ${i+1}`)):[],assignedEmployeeId:String(input.assignedEmployeeId||actor||""),territory:String(input.territory||"").trim(),routeName:String(input.routeName||"").trim(),paymentTermDays:Number(input.paymentTermDays||0),creditLimitPaise:Number(input.creditLimitPaise||0),creditHold:Boolean(input.creditHold),portalAccessEnabled:input.portalAccessEnabled!==false,status:input.status||"active",notes:String(input.notes||""),documentKeys:Array.isArray(input.documentKeys)?input.documentKeys:[],createdBy:actor,updatedBy:actor}); await syncUser(customer); return customer.toObject();}
async function update(customerId,input,actor){const current=await get(customerId); const patch={...input}; delete patch.customerId; if(input.mobile){patch.mobile=mobileValue(input.mobile);await ensureMobileAvailable(patch.mobile,customerId);patch.normalizedMobile=patch.mobile;} if(input.email!==undefined)patch.email=emailValue(input.email); if(input.billingAddress)patch.billingAddress=address(input.billingAddress,"Billing address"); if(Array.isArray(input.deliveryAddresses))patch.deliveryAddresses=input.deliveryAddresses.map((x,i)=>address(x,`Delivery address ${i+1}`)); patch.updatedBy=actor; const item=await Customer.findOneAndUpdate({customerId},{$set:patch},{new:true,runValidators:true}); await syncUser(item); return item.toObject();}
async function assigneeOptions(){return{items:await Employee.find({status:"active"}).sort({name:1}).limit(200).select({employeeId:1,name:1,employeeCode:1,designation:1,department:1}).lean()};}
module.exports={list,get,create,update,assigneeOptions,ensureMobileAvailable};
