const Employee=require("../models/Employee");const Role=require("../models/Role");const {pageQuery,escapedRegex}=require("../utils/pagination");const {mobileValue,emailValue,textValue}=require("../utils/validation");const {PERMISSION_GROUPS,isKnownPermission}=require("../utils/permissions");
function permissions(input){const list=Array.isArray(input)?[...new Set(input.map(String))]:[];if(list.some(x=>!isKnownPermission(x)))throw Object.assign(new Error("Role contains an unknown permission"),{status:400});return list;}
async function listEmployees(query={}){const{page,limit,skip}=pageQuery(query);const filter={};if(query.status)filter.status=query.status;if(query.search){const rx=new RegExp(escapedRegex(query.search),"i");filter.$or=[{name:rx},{mobile:rx},{employeeCode:rx},{department:rx}]};const[items,total]=await Promise.all([Employee.find(filter).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Employee.countDocuments(filter)]);return{items,page,limit,total,pages:Math.ceil(total/limit)||1};}
async function createEmployee(input,actor){const mobile=mobileValue(input.mobile);const role=await Role.findOne({roleId:input.roleId,active:true}).lean();if(!role)throw Object.assign(new Error("Role not found"),{status:404});return(await Employee.create({name:textValue(input.name,{label:"Name",required:true,maxLength:120}),mobile,normalizedMobile:mobile,email:emailValue(input.email),employeeCode:String(input.employeeCode||""),designation:String(input.designation||""),department:String(input.department||""),roleId:role.roleId,deliveryEligible:input.deliveryEligible!==false,status:input.status||"active",notes:String(input.notes||""),createdBy:actor,updatedBy:actor})).toObject();}
async function updateEmployee(id,input,actor){const current=await Employee.findOne({employeeId:id}).lean();if(!current)throw Object.assign(new Error("Employee not found"),{status:404});if(id===actor&&input.status&&input.status!=="active")throw Object.assign(new Error("You cannot deactivate or suspend your own employee account"),{status:409});const patch={updatedBy:actor};for(const key of["name","employeeCode","designation","department","status","notes","deliveryEligible"])if(Object.prototype.hasOwnProperty.call(input,key))patch[key]=input[key];if(input.mobile!==undefined){patch.mobile=mobileValue(input.mobile);patch.normalizedMobile=patch.mobile;}if(input.email!==undefined)patch.email=emailValue(input.email);if(input.roleId!==undefined){const role=await Role.findOne({roleId:input.roleId,active:true}).lean();if(!role)throw Object.assign(new Error("Role not found"),{status:404});patch.roleId=role.roleId;}return(await Employee.findOneAndUpdate({employeeId:id},{$set:patch},{new:true,runValidators:true})).toObject();}
async function listRoles(){return{items:await Role.find({}).sort({name:1}).limit(200).lean(),permissionGroups:PERMISSION_GROUPS};}
async function createRole(input,actor){return(await Role.create({name:textValue(input.name,{label:"Role name",required:true,maxLength:120}),slug:textValue(input.slug,{label:"Slug",required:true,maxLength:80}).toLowerCase(),description:String(input.description||""),permissions:permissions(input.permissions),active:input.active!==false,isSystem:false,isSuperAdmin:false,createdBy:actor,updatedBy:actor})).toObject();}
async function updateRole(id,input,actor){const current=await Role.findOne({roleId:id}).lean();if(!current)throw Object.assign(new Error("Role not found"),{status:404});if(current.isSuperAdmin){if(input.active===false)throw Object.assign(new Error("Super Admin role cannot be deactivated"),{status:409});if(input.permissions&&!permissions(input.permissions).includes("*"))throw Object.assign(new Error("Super Admin permissions cannot be reduced"),{status:400});}if(input.active===false){const assigned=await Employee.countDocuments({roleId:id,status:"active"});if(assigned>0)throw Object.assign(new Error("Role cannot be deactivated while active employees are assigned"),{status:409});}const patch={updatedBy:actor};for(const key of["name","slug","description","active"])if(Object.prototype.hasOwnProperty.call(input,key))patch[key]=input[key];if(input.permissions!==undefined)patch.permissions=permissions(input.permissions);return(await Role.findOneAndUpdate({roleId:id},{$set:patch},{new:true,runValidators:true})).toObject();}
module.exports={listEmployees,createEmployee,updateEmployee,listRoles,createRole,updateRole};
