const mongoose=require("mongoose");const CustomerPrice=require("../models/CustomerProductPrice");const Customer=require("../models/Customer");const Product=require("../models/Product");const CustomerProductMapping=require("../models/CustomerProductMapping");const {pageQuery}=require("../utils/pagination");const {requiredUuid,positiveInteger,nonNegativeInteger}=require("../utils/validation");const {hasPermission}=require("../utils/permissions");
async function list(query={}){const{page,limit,skip}=pageQuery(query);const filter={};if(query.customerId)filter.customerId=query.customerId;if(query.productId)filter.productId=query.productId;if(query.approvalStatus)filter.approvalStatus=query.approvalStatus;const[items,total]=await Promise.all([CustomerPrice.find(filter).sort({createdAt:-1}).skip(skip).limit(limit).lean(),CustomerPrice.countDocuments(filter)]);return{items,page,limit,total,pages:Math.ceil(total/limit)||1};}
async function create(input,admin){const customerId=requiredUuid(input.customerId,"Customer"),productId=requiredUuid(input.productId,"Product");const[customer,product]=await Promise.all([Customer.findOne({customerId,status:"active"}).lean(),Product.findOne({productId,status:"active"}).lean()]);if(!customer||!product)throw Object.assign(new Error("Customer or product was not found"),{status:404});const price=nonNegativeInteger(input.unitPricePaise,"Negotiated price");if(price<product.minimumSellingPricePaise)throw Object.assign(new Error("Negotiated price is below the minimum permitted selling price"),{status:400,code:"BELOW_MINIMUM_PRICE"});const minimumQuantity=positiveInteger(input.minimumQuantity??1,"Minimum quantity"),validFrom=input.validFrom?new Date(input.validFrom):new Date(),validUntil=input.validUntil?new Date(input.validUntil):null;if(Number.isNaN(validFrom.getTime())||(validUntil&&Number.isNaN(validUntil.getTime())))throw Object.assign(new Error("Price validity date is invalid"),{status:400});if(validUntil&&validUntil<validFrom)throw Object.assign(new Error("Price valid-until date cannot be before valid-from date"),{status:400});const requiresApproval=price<product.referenceSellingPricePaise&&!hasPermission(admin,"pricing.approve"),approvalStatus=requiresApproval?"pending":"approved";const session=await mongoose.startSession();try{return await session.withTransaction(async()=>{if(approvalStatus==="approved"&&input.replaceActive!==false)await CustomerPrice.updateMany({customerId,productId,active:true,approvalStatus:"approved"},{$set:{active:false,approvalStatus:"expired",updatedBy:admin.employeeId}},{session,runValidators:true});const rows=await CustomerPrice.create([{customerId,productId,unitPricePaise:price,minimumQuantity,validFrom,validUntil,approvalStatus,approvedBy:approvalStatus==="approved"?admin.employeeId:"",approvedAt:approvalStatus==="approved"?new Date():null,negotiatedBy:admin.employeeId,reason:String(input.reason||""),active:true,createdBy:admin.employeeId,updatedBy:admin.employeeId}],{session});return rows[0].toObject();});}finally{await session.endSession();}}
async function approve(id,admin,status="approved"){if(!hasPermission(admin,"pricing.approve"))throw Object.assign(new Error("Pricing approval permission is required"),{status:403});if(!["approved","rejected"].includes(status))throw Object.assign(new Error("Pricing decision must be approved or rejected"),{status:400});const session=await mongoose.startSession();try{return await session.withTransaction(async()=>{const item=await CustomerPrice.findOne({customerProductPriceId:id}).session(session);if(!item)throw Object.assign(new Error("Price agreement not found"),{status:404});if(item.approvalStatus!=="pending")throw Object.assign(new Error("Only pending price agreements can be decided"),{status:409});if(status==="approved"){await CustomerPrice.updateMany({customerId:item.customerId,productId:item.productId,customerProductPriceId:{$ne:item.customerProductPriceId},active:true,approvalStatus:"approved"},{$set:{active:false,approvalStatus:"expired",updatedBy:admin.employeeId}},{session,runValidators:true});item.active=true;}else item.active=false;item.approvalStatus=status;item.approvedBy=admin.employeeId;item.approvedAt=new Date();item.updatedBy=admin.employeeId;await item.save({session});return item.toObject();});}finally{await session.endSession();}}
// Shared eligibility rules keep the sales-order preview and creation consistent.
function effectiveAgreementQuery(customerId,productId,now=new Date()){
  return {customerId,productId,active:true,approvalStatus:"approved",validFrom:{$lte:now},$or:[{validUntil:null},{validUntil:{$gte:now}}]};
}
async function orderPrice(input={}){
  const customerId=requiredUuid(input.customerId,"Customer"),productId=requiredUuid(input.productId,"Product"),quantity=positiveInteger(input.quantity,"Quantity");
  const [customer,product,mapping,agreement]=await Promise.all([
    Customer.findOne({customerId,status:"active"}).select({customerId:1}).lean(),
    Product.findOne({productId,status:"active"}).select({productId:1,referenceSellingPricePaise:1,minimumSellingPricePaise:1}).lean(),
    CustomerProductMapping.findOne({customerId,productId,active:true}).select({customerProductMappingId:1}).lean(),
    CustomerPrice.findOne({...effectiveAgreementQuery(customerId,productId),minimumQuantity:{$lte:quantity}}).sort({validFrom:-1,createdAt:-1,customerProductPriceId:1}).lean()
  ]);
  if(!customer||!product)throw Object.assign(new Error("Customer or product was not found"),{status:404});
  if(!mapping)throw Object.assign(new Error("This product is not mapped to the selected customer"),{status:400,code:"CUSTOMER_PRODUCT_NOT_MAPPED"});
  const unitPricePaise=agreement?.unitPricePaise??product.referenceSellingPricePaise;
  if(unitPricePaise<product.minimumSellingPricePaise)throw Object.assign(new Error("The agreed price is below the current product minimum. Enter a permitted price or update the agreement."),{status:400,code:"BELOW_MINIMUM_PRICE"});
  return {customerId,productId,quantity,unitPricePaise,source:agreement?"negotiated":"reference",customerProductPriceId:agreement?.customerProductPriceId||""};
}
module.exports={list,create,approve,effectiveAgreementQuery,orderPrice};
