const SalesOrder=require("../models/SalesOrder");
const ProcurementAllocation=require("../models/ProcurementAllocation");
const Payment=require("../models/Payment");
const Invoice=require("../models/Invoice");
const SupplierBill=require("../models/SupplierBill");
const Return=require("../models/Return");
const Employee=require("../models/Employee");const {applyScope}=require("../utils/access-scope");
function range(query={}){const from=query.from?new Date(String(query.from)+"T00:00:00.000Z"):new Date(Date.now()-30*86400000);const to=query.to?new Date(String(query.to)+"T23:59:59.999Z"):new Date();if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to)throw Object.assign(new Error("Report date range is invalid"),{status:400});if(to-from>366*86400000)throw Object.assign(new Error("Report date range cannot exceed 366 days"),{status:400});return{from,to};}
function chunk(values,size=500){const out=[];for(let i=0;i<values.length;i+=size)out.push(values.slice(i,i+size));return out;}
async function allocationRows(orderIds){const rows=[];for(const ids of chunk(orderIds)){const part=await ProcurementAllocation.aggregate([{$match:{salesOrderId:{$in:ids},status:{$ne:"cancelled"}}},{$group:{_id:{salesOrderId:"$salesOrderId",supplierId:"$supplierId"},quantity:{$sum:"$quantity"},procurementCostPaise:{$sum:{$multiply:["$purchasePricePaise","$quantity"]}},supplierName:{$first:"$supplierSnapshot.businessName"}}}]);rows.push(...part);}return rows;}
async function sumField(Model,match,field){const rows=await Model.aggregate([{$match:match},{$group:{_id:null,total:{$sum:`$${field}`}}}]);return Number(rows[0]?.total||0);}
async function countAndSum(Model,match,field){const rows=await Model.aggregate([{$match:match},{$group:{_id:null,count:{$sum:1},total:{$sum:`$${field}`}}}]);return{count:Number(rows[0]?.count||0),total:Number(rows[0]?.total||0)};}
async function businessSummary(query={}){
  const{from,to}=range(query),date={$gte:from,$lte:to},orderMatch={createdAt:date,status:{$ne:"cancelled"},orderType:{$ne:"replacement"}};
  const[orders,invoiceAgg,receivablePayments,supplierPayments,billAgg,returnCount,currentReceivableOutstandingPaise,currentPayableOutstandingPaise]=await Promise.all([
    SalesOrder.aggregate([{$match:orderMatch},{$project:{_id:0,salesOrderId:1,assignedEmployeeId:1,status:1,taxablePaise:{$ifNull:["$taxablePaise",0]},gstPaise:{$ifNull:["$gstPaise",0]},stockCostPaise:{$sum:{$map:{input:{$ifNull:["$lines",[]]},as:"line",in:{$multiply:[{$ifNull:["$$line.stockReservedQty",0]},{$ifNull:["$$line.stockUnitCostPaise",0]}]}}}}}}]),
    countAndSum(Invoice,{createdAt:date,status:"issued"},"totalPaise"),
    sumField(Payment,{paidAt:date,direction:"receivable"},"amountPaise"),
    sumField(Payment,{paidAt:date,direction:"payable"},"amountPaise"),
    countAndSum(SupplierBill,{createdAt:date,paymentStatus:{$ne:"void"}},"totalPaise"),
    Return.countDocuments({createdAt:date}),
    sumField(Invoice,{status:"issued",outstandingPaise:{$gt:0}},"outstandingPaise"),
    sumField(SupplierBill,{paymentStatus:{$in:["unpaid","partially_paid","settled"]},outstandingPaise:{$gt:0}},"outstandingPaise"),
  ]);
  const orderIds=orders.map(x=>x.salesOrderId),allocations=orderIds.length?await allocationRows(orderIds):[],procurementCostByOrder=new Map(),suppliers=new Map();
  for(const row of allocations){const orderId=row._id.salesOrderId,supplierId=row._id.supplierId,cost=Number(row.procurementCostPaise||0);procurementCostByOrder.set(orderId,(procurementCostByOrder.get(orderId)||0)+cost);const v=suppliers.get(supplierId)||{supplierId,supplierName:row.supplierName||"",allocationCount:0,quantity:0,procurementCostPaise:0};v.allocationCount+=1;v.quantity+=Number(row.quantity||0);v.procurementCostPaise+=cost;suppliers.set(supplierId,v);}
  const employeeIds=[...new Set(orders.map(o=>o.assignedEmployeeId).filter(Boolean))],employeeRows=employeeIds.length?await Employee.find({employeeId:{$in:employeeIds}}).select({employeeId:1,name:1,employeeCode:1}).lean():[],employeeNames=new Map(employeeRows.map(e=>[e.employeeId,e.name||e.employeeCode||e.employeeId]));
  let netSalesPaise=0,salesGstPaise=0,stockCostPaise=0,procurementCostPaise=0;const agents=new Map(),statuses={};
  for(const o of orders){const sale=Number(o.taxablePaise||0),stock=Number(o.stockCostPaise||0),procurement=Number(procurementCostByOrder.get(o.salesOrderId)||0),id=o.assignedEmployeeId||"unassigned";netSalesPaise+=sale;salesGstPaise+=Number(o.gstPaise||0);stockCostPaise+=stock;procurementCostPaise+=procurement;statuses[o.status]=(statuses[o.status]||0)+1;const v=agents.get(id)||{employeeId:id,employeeName:id==="unassigned"?"Unassigned":employeeNames.get(id)||"Unknown employee",orderCount:0,netSalesPaise:0,stockCostPaise:0,procurementCostPaise:0,cogsPaise:0,grossMarginPaise:0};v.orderCount+=1;v.netSalesPaise+=sale;v.stockCostPaise+=stock;v.procurementCostPaise+=procurement;v.cogsPaise=v.stockCostPaise+v.procurementCostPaise;v.grossMarginPaise=v.netSalesPaise-v.cogsPaise;agents.set(id,v);}
  const cogsPaise=stockCostPaise+procurementCostPaise;
  return{from,to,salesOrderCount:orders.length,netSalesPaise,salesGstPaise,stockCostPaise,procurementCostPaise,cogsPaise,grossMarginPaise:netSalesPaise-cogsPaise,invoicedPaise:invoiceAgg.total,invoiceCount:invoiceAgg.count,customerCollectionsPaise:receivablePayments,supplierPaymentsPaise:supplierPayments,supplierBillsPaise:billAgg.total,supplierBillCount:billAgg.count,currentReceivableOutstandingPaise,currentPayableOutstandingPaise,returnCount,orderStatusCounts:statuses,agentPerformance:[...agents.values()].sort((a,b)=>b.netSalesPaise-a.netSalesPaise),supplierPerformance:[...suppliers.values()].sort((a,b)=>b.procurementCostPaise-a.procurementCostPaise)};
}
function csvCell(value){const s=String(value??"");return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function toCsv(report){const rows=[["Metric","Value"],["From",report.from.toISOString()],["To",report.to.toISOString()],["Sales order count",report.salesOrderCount],["Net sales paise",report.netSalesPaise],["Sales GST paise",report.salesGstPaise],["Existing-stock cost paise",report.stockCostPaise],["Procurement cost paise",report.procurementCostPaise],["COGS paise",report.cogsPaise],["Gross margin paise",report.grossMarginPaise],["Customer collections paise",report.customerCollectionsPaise],["Supplier payments paise",report.supplierPaymentsPaise],["Receivable outstanding paise",report.currentReceivableOutstandingPaise],["Payable outstanding paise",report.currentPayableOutstandingPaise],["Return count",report.returnCount],[],["Sales employee","Employee ID","Orders","Net sales paise","Existing-stock cost paise","Procurement cost paise","COGS paise","Gross margin paise"],...report.agentPerformance.map(x=>[x.employeeName,x.employeeId,x.orderCount,x.netSalesPaise,x.stockCostPaise,x.procurementCostPaise,x.cogsPaise,x.grossMarginPaise]),[],["Supplier ID","Supplier","Allocation groups","Quantity","Procurement cost paise"],...report.supplierPerformance.map(x=>[x.supplierId,x.supplierName,x.allocationCount,x.quantity,x.procurementCostPaise])];return rows.map(row=>row.map(csvCell).join(",")).join("\n");}
module.exports={businessSummary,toCsv};
