const mongoose=require("mongoose");const Return=require("../models/Return");const ReturnSettlement=require("../models/ReturnSettlement");const SalesOrder=require("../models/SalesOrder");const PurchaseOrder=require("../models/PurchaseOrder");const GoodsReceipt=require("../models/GoodsReceipt");const Warehouse=require("../models/Warehouse");const Delivery=require("../models/DeliveryAssignment");const InventoryBalance=require("../models/InventoryBalance");const InventoryMovement=require("../models/InventoryMovement");const Invoice=require("../models/Invoice");const SupplierBill=require("../models/SupplierBill");const uuid=require("../utils/uuid");const {multiplyPaise,gstPaise}=require("../utils/money");const {pageQuery}=require("../utils/pagination");const {positiveInteger}=require("../utils/validation");
function replacementOrderNumber(){return `RO-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${uuid().slice(0,8).toUpperCase()}`;}
async function list(query={}){const{page,limit,skip}=pageQuery(query);const filter={};if(query.status)filter.status=query.status;if(query.returnType)filter.returnType=query.returnType;const[items,total]=await Promise.all([Return.find(filter).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Return.countDocuments(filter)]);return{items,page,limit,total,pages:Math.ceil(total/limit)||1};}
async function create(input,actor){
  const returnType=String(input.returnType||"");
  if(!["customer","supplier"].includes(returnType))throw Object.assign(new Error("Return type is invalid"),{status:400});
  if(!Array.isArray(input.lines)||!input.lines.length)throw Object.assign(new Error("Return lines are required"),{status:400});
  const warehouseId=String(input.warehouseId||"");const warehouse=await Warehouse.findOne({warehouseId,active:true}).select({warehouseId:1}).lean();if(!warehouse)throw Object.assign(new Error("Return warehouse was not found or is inactive"),{status:404});
  let customerId="",supplierId="",sourceLines=[],sourceId="",sourceField="";
  if(returnType==="customer"){
    const order=await SalesOrder.findOne({salesOrderId:input.salesOrderId}).lean();
    if(!order)throw Object.assign(new Error("Sales order not found"),{status:404});
    if(!["delivered","partially_delivered"].includes(order.status))throw Object.assign(new Error("Customer returns can only be created for delivered or partially delivered orders"),{status:409});
    customerId=order.customerId;sourceId=order.salesOrderId;sourceField="salesOrderId";
    let deliveredByLine=null;
    if(order.status==="partially_delivered"){
      const delivery=await Delivery.findOne({salesOrderId:order.salesOrderId,status:"partially_delivered"}).sort({createdAt:-1}).lean();
      if(delivery?.lines?.length)deliveredByLine=new Map(delivery.lines.map(line=>[line.salesOrderLineId,Number(line.deliveredQty||0)]));
    }
    const sourceMap=new Map();for(const line of order.lines||[]){const maxQty=deliveredByLine?Number(deliveredByLine.get(line.salesOrderLineId)||0):Number(line.quantity||0),current=sourceMap.get(line.productId)||{productId:line.productId,productName:line.productName,maxQty:0};current.maxQty+=maxQty;sourceMap.set(line.productId,current);}sourceLines=[...sourceMap.values()];
  }else{
    const po=await PurchaseOrder.findOne({purchaseOrderId:input.purchaseOrderId}).lean();
    if(!po)throw Object.assign(new Error("Purchase order not found"),{status:404});
    if(!["partially_received","received","closed"].includes(po.status))throw Object.assign(new Error("Supplier returns require received purchase-order stock"),{status:409});
    supplierId=po.supplierId;sourceId=po.purchaseOrderId;sourceField="purchaseOrderId";
    const receipts=await GoodsReceipt.find({purchaseOrderId:po.purchaseOrderId}).select({lines:1}).lean(),sourceMap=new Map();for(const receipt of receipts)for(const line of receipt.lines||[]){const eligible=Number(line.acceptedQty||0)+Number(line.damagedQty||0),current=sourceMap.get(line.productId)||{productId:line.productId,productName:(po.lines||[]).find(x=>x.productId===line.productId)?.productName||"Product",maxQty:0};current.maxQty+=eligible;sourceMap.set(line.productId,current);}sourceLines=[...sourceMap.values()];
  }
  const prior=await Return.find({returnType,[sourceField]:sourceId,status:{$ne:"rejected"}}).sort({createdAt:-1}).limit(500).lean();
  const alreadyReturned=new Map();for(const item of prior)for(const line of item.lines||[]){if(line.outcome==="rejected")continue;alreadyReturned.set(line.productId,(alreadyReturned.get(line.productId)||0)+Number(line.quantity||0));}
  const sourceByProduct=new Map(sourceLines.map(line=>[line.productId,line]));
  const normalized=input.lines.map(raw=>{const source=sourceByProduct.get(String(raw.productId||""));if(!source||source.maxQty<=0)throw Object.assign(new Error("Return product is not eligible on the source document"),{status:400});const quantity=positiveInteger(raw.quantity,"Return quantity"),used=Number(alreadyReturned.get(source.productId)||0);if(used+quantity>source.maxQty)throw Object.assign(new Error(`Return quantity exceeds eligible quantity for ${source.productName}`),{status:409});alreadyReturned.set(source.productId,used+quantity);const sourceBucket=["available","damaged","returned"].includes(String(raw.sourceBucket||""))?String(raw.sourceBucket):"available";return{productId:source.productId,productName:source.productName,quantity,reason:String(raw.reason||"Return"),sourceBucket,outcome:"pending"};});
  const item=await Return.create({returnType,salesOrderId:returnType==="customer"?sourceId:"",purchaseOrderId:returnType==="supplier"?sourceId:"",customerId,supplierId,warehouseId,status:"requested",lines:normalized,documentKeys:Array.isArray(input.documentKeys)?input.documentKeys:[],notes:String(input.notes||""),createdBy:actor,updatedBy:actor});return item.toObject();
}
async function receiveCustomerStock(item,line,outcome,actor,session){const bucket=outcome==="sellable"?"available":outcome==="damaged"?"damaged":"returned",field={available:"availableQty",damaged:"damagedQty",returned:"returnedQty"}[bucket];await InventoryBalance.findOneAndUpdate({warehouseId:item.warehouseId,productId:line.productId},{$inc:{[field]:line.quantity},$set:{updatedBy:actor}},{upsert:true,new:true,session,setDefaultsOnInsert:true});await InventoryMovement.create([{warehouseId:item.warehouseId,productId:line.productId,movementType:"customer_return",quantityDelta:line.quantity,bucket,referenceType:"return",referenceId:item.returnId,reason:`Customer return: ${outcome}`,actorEmployeeId:actor}],{session});}
async function createCustomerSettlement(item,creditLines,actor,session){if(!creditLines.length)return null;const order=await SalesOrder.findOne({salesOrderId:item.salesOrderId}).session(session).lean();if(!order)throw Object.assign(new Error("Source sales order not found"),{status:404});const invoice=await Invoice.findOne({salesOrderId:item.salesOrderId,status:"issued"}).session(session);let amount=0;for(const line of creditLines){const source=invoice?.lines?.find(x=>x.productId===line.productId)||order.lines?.find(x=>x.productId===line.productId);if(!source)throw Object.assign(new Error("Return credit source line was not found"),{status:409});const taxable=multiplyPaise(Number(source.unitPricePaise||0),line.quantity),gst=gstPaise(taxable,Number(source.gstRateBps||0));amount+=taxable+gst;}let applied=0;if(invoice&&amount>0){applied=Math.min(amount,Number(invoice.outstandingPaise||0));invoice.creditedPaise=Number(invoice.creditedPaise||0)+applied;invoice.outstandingPaise-=applied;if(invoice.outstandingPaise===0)invoice.paymentStatus=Number(invoice.paidPaise||0)>0?"paid":"settled";else invoice.paymentStatus=Number(invoice.paidPaise||0)>0?"partially_paid":"unpaid";await invoice.save({session});}const rows=await ReturnSettlement.create([{returnId:item.returnId,settlementType:"customer_credit",customerId:item.customerId,salesOrderId:item.salesOrderId,invoiceId:invoice?.invoiceId||"",amountPaise:amount,appliedPaise:applied,unappliedPaise:Math.max(0,amount-applied),status:amount===applied?"applied":applied>0?"partially_applied":"open",notes:"Customer return credit note",createdBy:actor}],{session});return rows[0];}
async function createSupplierSettlement(item,supplierLines,actor,session){if(!supplierLines.length)return null;const po=await PurchaseOrder.findOne({purchaseOrderId:item.purchaseOrderId}).session(session).lean();if(!po)throw Object.assign(new Error("Source purchase order not found"),{status:404});let amount=0;for(const line of supplierLines){const source=po.lines?.find(x=>x.productId===line.productId);if(!source)throw Object.assign(new Error("Supplier return source line was not found"),{status:409});const taxable=multiplyPaise(Number(source.unitPurchasePricePaise||0),line.quantity),gst=source.gstCharged?gstPaise(taxable,Number(source.gstRateBps||0)):0;amount+=taxable+gst;}let remaining=amount,applied=0;const billIds=[];const bills=await SupplierBill.find({purchaseOrderId:item.purchaseOrderId,supplierId:item.supplierId,paymentStatus:{$ne:"void"},outstandingPaise:{$gt:0}}).sort({createdAt:1}).session(session);for(const bill of bills){if(remaining<=0)break;const use=Math.min(remaining,Number(bill.outstandingPaise||0));if(!use)continue;bill.debitedPaise=Number(bill.debitedPaise||0)+use;bill.outstandingPaise-=use;if(bill.outstandingPaise===0)bill.paymentStatus=Number(bill.paidPaise||0)>0?"paid":"settled";else bill.paymentStatus=Number(bill.paidPaise||0)>0?"partially_paid":"unpaid";await bill.save({session});remaining-=use;applied+=use;billIds.push(bill.supplierBillId);}const rows=await ReturnSettlement.create([{returnId:item.returnId,settlementType:"supplier_debit",supplierId:item.supplierId,purchaseOrderId:item.purchaseOrderId,supplierBillIds:billIds,amountPaise:amount,appliedPaise:applied,unappliedPaise:Math.max(0,amount-applied),status:amount===applied?"applied":applied>0?"partially_applied":"open",notes:"Supplier return debit note",createdBy:actor}],{session});return rows[0];}
async function createReplacementOrder(item,replacementLines,actor,session){if(!replacementLines.length)return null;const source=await SalesOrder.findOne({salesOrderId:item.salesOrderId}).session(session).lean();if(!source)throw Object.assign(new Error("Source sales order not found"),{status:404});const byProduct=new Map(source.lines.map(x=>[x.productId,x]));const lines=replacementLines.map(line=>{const original=byProduct.get(line.productId);if(!original)throw Object.assign(new Error("Replacement source line was not found"),{status:409});return{productId:line.productId,productName:original.productName,sku:original.sku,hsnCode:original.hsnCode||"",quantity:line.quantity,unitPricePaise:0,gstRateBps:0,customerProductPriceId:"",minimumSellingPricePaise:0,priceException:false,stockReservedQty:0,stockUnitCostPaise:0,procurementRequiredQty:0};});const rows=await SalesOrder.create([{orderNumber:replacementOrderNumber(),orderType:"replacement",sourceReturnId:item.returnId,customerId:source.customerId,customerSnapshot:source.customerSnapshot,deliveryAddressSnapshot:source.deliveryAddressSnapshot,assignedEmployeeId:source.assignedEmployeeId,warehouseId:item.warehouseId,status:"created",approvalStatus:"not_required",approvalReasons:[],lines,taxablePaise:0,gstPaise:0,gstTreatment:"no_gst",totalPaise:0,paymentTermDays:0,paymentDueAt:new Date(),notes:`Replacement order generated from return ${item.returnId}`,createdBy:actor,updatedBy:actor}],{session});return rows[0];}
async function process(id,input,actor){const session=await mongoose.startSession();try{return await session.withTransaction(async()=>{const item=await Return.findOne({returnId:id}).session(session);if(!item)throw Object.assign(new Error("Return not found"),{status:404});if(!["approved","received","requested"].includes(item.status))throw Object.assign(new Error("Return cannot be processed"),{status:409});const creditLines=[],replacementLines=[],supplierDebitLines=[];for(const line of item.lines){const outcome=String((input.outcomes||{})[line.returnLineId]||line.outcome||"pending"),allowed=item.returnType==="customer"?["sellable","damaged","replacement","credit_note","rejected"]:["supplier_return","rejected"];if(!allowed.includes(outcome))throw Object.assign(new Error(`Return outcome ${outcome} is invalid for ${item.returnType} return`),{status:400});line.outcome=outcome;if(item.returnType==="customer"&&outcome!=="rejected"){await receiveCustomerStock(item,line,outcome,actor,session);if(outcome==="credit_note")creditLines.push(line);if(outcome==="replacement")replacementLines.push(line);}if(item.returnType==="supplier"&&outcome==="supplier_return"){const sourceBucket=String(line.sourceBucket||"available"),field={available:"availableQty",damaged:"damagedQty",returned:"returnedQty"}[sourceBucket];if(!field)throw Object.assign(new Error("Supplier return source bucket is invalid"),{status:400});const balance=await InventoryBalance.findOne({warehouseId:item.warehouseId,productId:line.productId}).session(session);if(!balance||Number(balance[field]||0)<line.quantity)throw Object.assign(new Error(`Insufficient ${sourceBucket} stock for supplier return of ${line.productName}`),{status:409});balance[field]-=line.quantity;balance.updatedBy=actor;await balance.save({session});await InventoryMovement.create([{warehouseId:item.warehouseId,productId:line.productId,movementType:"supplier_return",quantityDelta:-line.quantity,bucket:sourceBucket,referenceType:"return",referenceId:item.returnId,reason:"Stock returned to supplier",actorEmployeeId:actor}],{session});supplierDebitLines.push(line);}}
const settlement=item.returnType==="customer"?await createCustomerSettlement(item,creditLines,actor,session):await createSupplierSettlement(item,supplierDebitLines,actor,session);const replacement=item.returnType==="customer"?await createReplacementOrder(item,replacementLines,actor,session):null;if(settlement)item.returnSettlementId=settlement.returnSettlementId;if(replacement)item.replacementSalesOrderId=replacement.salesOrderId;item.status="processed";item.updatedBy=actor;await item.save({session});return{...item.toObject(),settlement:settlement?.toObject?.()||settlement||null,replacementOrder:replacement?.toObject?.()||replacement||null};});}finally{await session.endSession();}}
module.exports={list,create,process};
