const crypto=require("crypto"); const Employee=require("../models/Employee"); const Role=require("../models/Role"); const {hasPermission}=require("../utils/permissions");
const cookieName=process.env.AUTH_COOKIE_NAME||"findoly_b2b_admin"; const SESSION_MS=24*60*60*1000;
function secret(){return String(process.env.AUTH_COOKIE_SECRET||"findoly-b2b-development-cookie-secret-change-me");}
function sign(v){return crypto.createHmac("sha256",secret()).update(v).digest("base64url");} function csrfTokenForSession(session){return sign(`csrf:${session.employeeId}:${session.iat}:${session.exp}`);}
function encodeSession(session){const payload=Buffer.from(JSON.stringify(session)).toString("base64url"); return `${payload}.${sign(payload)}`;}
function decodeSession(raw){const [payload,sig,extra]=String(raw||"").split("."); if(!payload||!sig||extra){throw new Error("Invalid session");} const a=Buffer.from(sig),b=Buffer.from(sign(payload)); if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw new Error("Invalid session"); const s=JSON.parse(Buffer.from(payload,"base64url").toString("utf8")); if(s.v!==1||!s.employeeId||!Number.isFinite(s.exp))throw new Error("Invalid session"); return s;}
function cookieOptions(){return{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:SESSION_MS};}
function clearAdminCookie(res){res.clearCookie(cookieName,{...cookieOptions(),maxAge:undefined});}
function setAdminCookie(res,access){const now=Date.now(); const s={v:1,...access,iat:now,exp:now+SESSION_MS}; res.cookie(cookieName,encodeSession(s),cookieOptions()); return s;}
async function loadAccess(s){if(process.env.NODE_ENV==="test"&&process.env.SKIP_DB==="true")return s; const employee=await Employee.findOne({employeeId:s.employeeId,status:"active"}).lean(); if(!employee)return null; const role=await Role.findOne({roleId:employee.roleId,active:true}).lean(); if(!role)return null; return {employeeId:employee.employeeId,name:employee.name,mobile:employee.mobile,email:employee.email||"",employeeCode:employee.employeeCode||"",designation:employee.designation||"",department:employee.department||"",roleId:role.roleId,roleName:role.name,permissions:role.permissions||[],iat:s.iat,exp:s.exp};}
async function attachAdmin(req,res,next){req.admin=null;res.locals.currentAdmin=null;res.locals.csrfToken="";res.locals.homePath="/login";res.locals.can=()=>false; const raw=req.cookies?.[cookieName]; if(!raw)return next(); try{const s=decodeSession(raw); if(s.exp<=Date.now()){clearAdminCookie(res);return next();} const current=await loadAccess(s); if(!current){clearAdminCookie(res);return next();} req.admin=current;res.locals.currentAdmin=current;res.locals.homePath=firstAuthorizedPath(current);res.locals.csrfToken=csrfTokenForSession(current);res.locals.can=p=>hasPermission(current,p);return next();}catch(_){clearAdminCookie(res);return next();}}
function pageAuth(req,res,next){return req.admin?next():res.redirect(`/login?returnTo=${encodeURIComponent(req.originalUrl||"/dashboard")}`);}
const HOME_DESTINATIONS=[["dashboard.view","/dashboard"],["orders.view","/orders"],["orders.create","/orders/new"],["customers.view","/customers"],["products.view","/products"],["procurement.view","/procurement"],["inventory.view","/inventory"],["delivery.view","/delivery"],["finance.view","/finance"],["suppliers.view","/suppliers"],["pricing.view","/pricing"],["returns.view","/returns"],["reports.view","/reports"],["employees.view","/employees"],["roles.view","/roles"],["storage.view","/storage"],["audit.view","/audit"]];
function firstAuthorizedPath(admin){return HOME_DESTINATIONS.find(([permission])=>hasPermission(admin,permission))?.[1]||"/access-denied";}
function guestOnly(req,res,next){return req.admin?res.redirect(firstAuthorizedPath(req.admin)):next();}
function apiAuth(req,res,next){return req.admin?next():res.status(401).json({success:false,code:"AUTHENTICATION_REQUIRED",message:"Authentication required"});}
function requirePermission(permission){return(req,res,next)=>{if(hasPermission(req.admin,permission))return next(); if(req.originalUrl.startsWith("/api/"))return res.status(403).json({success:false,code:"FORBIDDEN",message:"You do not have permission to perform this action"}); return res.status(403).render("error",{title:"Access denied",message:"You do not have permission to access this feature."});};}
function requireAnyPermission(...permissions){return(req,res,next)=>{if(permissions.some(permission=>hasPermission(req.admin,permission)))return next(); if(req.originalUrl.startsWith("/api/"))return res.status(403).json({success:false,code:"FORBIDDEN",message:"You do not have permission to perform this action"}); return res.status(403).render("error",{title:"Access denied",message:"You do not have permission to access this feature."});};}
module.exports={attachAdmin,pageAuth,guestOnly,apiAuth,requirePermission,requireAnyPermission,setAdminCookie,clearAdminCookie,encodeSession,decodeSession,csrfTokenForSession,firstAuthorizedPath,SESSION_MS};
